import type { GeneratedReportContent } from "@/utils/report/types";
import type { AuditItemDto } from "@/utils/dto/types";
import type { UseCase } from "@/utils/audit/types";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatMoney(n: number): string {
  const v = Number.isFinite(n) ? n : 0;
  return v.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

function formatToolName(name: string): string {
  return name.replace(/_/g, " ");
}

export type AuditPdfHtmlContext = {
  generatedContent: GeneratedReportContent;
  publicId: string;
  createdAt: string;
  teamSize: number;
  primaryUseCase: UseCase;
  totalMonthlySpend: number;
  totalMonthlySavings: number;
  totalAnnualSavings: number;
  auditScore: number;
  summary: string;
  items: AuditItemDto[];
  leadFirstName: string;
  leadLastName: string;
  leadCompany: string;
};

export function buildAuditReportPdfHtml(ctx: AuditPdfHtmlContext): string {
  const c = ctx.generatedContent;
  const recipient = escapeHtml(`${ctx.leadFirstName} ${ctx.leadLastName}`.trim());
  const company = escapeHtml(ctx.leadCompany);

  const oppRows = c.topOpportunities
    .map(
      (o) => `
      <tr>
        <td style="padding:8px;border:1px solid #e2e8f0;vertical-align:top;"><strong>${escapeHtml(o.title)}</strong></td>
        <td style="padding:8px;border:1px solid #e2e8f0;">${escapeHtml(o.summary)}</td>
      </tr>`
    )
    .join("");

  const toolRows = ctx.items
    .map(
      (i) => `
      <tr>
        <td style="padding:8px;border:1px solid #e2e8f0;">${escapeHtml(formatToolName(i.toolName))}</td>
        <td style="padding:8px;border:1px solid #e2e8f0;">${escapeHtml(formatToolName(i.recommendationType))}</td>
        <td style="padding:8px;border:1px solid #e2e8f0;text-align:right;">$${formatMoney(i.monthlySavings)}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>AI spend audit — ${escapeHtml(ctx.publicId)}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; color: #0f172a; margin: 0; padding: 32px; font-size: 12px; line-height: 1.5; }
    h1 { font-size: 22px; margin: 0 0 8px; }
    h2 { font-size: 15px; margin: 24px 0 10px; color: #047857; }
    .muted { color: #64748b; }
    .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 16px 0; }
    .card { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px; background: #fafafa; }
    .card b { display: block; font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: .06em; }
    .card span { font-size: 16px; font-weight: 700; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #64748b; padding: 8px; border-bottom: 1px solid #e2e8f0; }
  </style>
</head>
<body>
  <p class="muted" style="margin:0 0 16px;">Prepared for ${recipient} · ${company}</p>
  <h1>AI spend audit report</h1>
  <p class="muted" style="margin:0 0 20px;">Report ID ${escapeHtml(ctx.publicId)} · ${escapeHtml(ctx.createdAt.slice(0, 10))}</p>

  <div class="grid">
    <div class="card"><b>Monthly spend</b><span>$${formatMoney(ctx.totalMonthlySpend)}</span></div>
    <div class="card"><b>Monthly savings</b><span>$${formatMoney(ctx.totalMonthlySavings)}</span></div>
    <div class="card"><b>Annual savings</b><span>$${formatMoney(ctx.totalAnnualSavings)}</span></div>
    <div class="card"><b>Score</b><span>${ctx.auditScore}/100</span></div>
  </div>

  <h2>Executive summary</h2>
  <p>${escapeHtml(ctx.summary)}</p>
  <p>${escapeHtml(c.executiveSummary)}</p>

  <h2>Stack overview</h2>
  <p>${escapeHtml(c.stackOverviewSummary)}</p>
  <p class="muted">Team size: ${ctx.teamSize} · Primary use case: ${escapeHtml(formatToolName(ctx.primaryUseCase))}</p>

  <h2>Top opportunities</h2>
  <table>
    <thead><tr><th>Opportunity</th><th>Details</th></tr></thead>
    <tbody>${oppRows}</tbody>
  </table>

  <h2>Benchmark insights</h2>
  <p><strong>Spend efficiency</strong> — ${escapeHtml(c.benchmarkInsights.spendEfficiency)}</p>
  <p><strong>Tool overlap</strong> — ${escapeHtml(c.benchmarkInsights.toolOverlap)}</p>
  <p><strong>Operational risk</strong> — ${escapeHtml(c.benchmarkInsights.operationalRisk)}</p>

  <h2>Per-tool recommendations</h2>
  <table>
    <thead><tr><th>Tool</th><th>Recommendation</th><th>Monthly savings</th></tr></thead>
    <tbody>${toolRows}</tbody>
  </table>

  <h2>Final recommendation</h2>
  <p>${escapeHtml(c.finalRecommendation)}</p>

  <p class="muted" style="margin-top:32px;">Generated by AuditMyAI. Figures are modeled from your submitted inputs.</p>
</body>
</html>`;
}
